// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9qccu0ew4wWuBX1LeDFlZFYFRPGwTENM',
    appId: '1:839774020308:android:2d7c824c989a150bb6d141',
    messagingSenderId: '839774020308',
    projectId: 'seasonbox-f4b24',
    storageBucket: 'seasonbox-f4b24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcg1iSRadP4jnG6iHRcS0YnGkDt3GUW74',
    appId: '1:839774020308:ios:8e360473f3ba0dbeb6d141',
    messagingSenderId: '839774020308',
    projectId: 'seasonbox-f4b24',
    storageBucket: 'seasonbox-f4b24.firebasestorage.app',
    iosBundleId: 'io.mos.seasonbox',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9qccu0ew4wWuBX1LeDFlZFYFRPGwTENM',
    appId: '1:839774020308:web:a6d9f7c8e9b0c1d2e3f4g5',
    messagingSenderId: '839774020308',
    projectId: 'seasonbox-f4b24',
    authDomain: 'seasonbox-f4b24.firebaseapp.com',
    storageBucket: 'seasonbox-f4b24.firebasestorage.app',
  );
}
